name: Renovate
on:
  schedule:
    - cron: "0 0 * * 0"  # Run weekly on Sundays at midnight
  workflow_dispatch:      # Allow manual triggering
  push:
    branches:
      - main            # Run on main branch updates
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/renovate.yml'
      - 'renovate.json'

jobs:
  renovate:
    runs-on: ubuntu-latest  # This uses GitHub-hosted runners (GitHub's infrastructure)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_AUTODISCOVER: true
          RENOVATE_PLATFORM: github
          RENOVATE_ONBOARDING: true
          RENOVATE_REPOSITORIES: ${{ github.repository }}

